apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zotprime-k8s.fullname" . }}-zotprime-ingress-websocket
  labels:
    apps: zotprime-ingress-websocket
  {{- include "zotprime-k8s.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt
    {{- end }}
spec:
  {{- if .Values.ingressClassName }}
  ingressClassName: {{ .Values.ingressClassName }}
  {{- end }}
  {{- if .Values.tls.enabled }}
  tls:
  - secretName: {{ include "zotprime-k8s.fullname" . }}-tls
    hosts:
    - {{ .Values.ingressHostnames.streamserver }}
  {{- end }}
  rules:
  - host: {{ .Values.ingressHostnames.streamserver }}
    http:
      paths:
      - backend:
          service:
            name: streamserver
            port:
              name: streamserver
        path: /
        pathType: Prefix
